# Uncomment the next line to define a global platform for your project
platform :ios, '13.0'

target 'TV Shows' do
  # Comment the next line if you don't want to use dynamic frameworks
  use_frameworks!

  
  # Pods for TV Shows
  pod 'MBProgressHUD'
  pod 'Alamofire'

end
